from pathlib import Path
import base64,html,json
R=Path(__file__).resolve().parent
pages=[
('home','Главная','/','Бумажный фон, PT Serif и одна колонка. Видеоблок сохранён перед статьями: ролик можно смотреть прямо на странице. Ниже идут свежие статьи, подборка автора и ссылки.'),
('post','Страница поста','/blog/best-practices-code/','Обложка расположена над заголовком. Заголовок и вступление сохранены. Оглавление идёт в тексте. Промпт свёрнут по умолчанию и раскрывается в правом поле на широком экране.'),
('blog','Блог и поиск','/blog/','Подборки оформлены простыми текстовыми ссылками. Поиск, список статей по месяцам и темы остаются на странице. В макете поиск работает по заголовкам; при внедрении сохраняется полный поисковый индекс.'),
('rich','Пост с графиками','/blog/claude-fable-5-1/','Эта статья уже использует бумажную типографику и меняет тему вместе с браузером. Будущий фрагмент показывает единую светлую оболочку, три переключаемых графика и промпт. Остальные разделы переносятся при реализации.'),
('about','Обо мне','/about/','Биография, обучение и контакты остаются в одной колонке с теми же размерами текста, что в статье.'),
('links','Мои ссылки','/links/','Группы сервисов, описания и действующие ссылки сохраняются. Меняются шрифт, цвет и отступы.'),
('tags','Темы','/tags/','Ссылки на темы и число статей получают спокойную моноширинную типографику. Адреса и режим индексации сохраняются.'),
('topic','Статьи по теме','/tags/claude-code/','Страница выбранной темы продолжает оформление блога: заголовок, список статей с датами и возврат.'),
('error','Страница ошибки','/404/','Короткое сообщение и переходы на главную и в блог. Здесь показан вид страницы ошибки; HTTP-статус отсутствующего адреса проверяется при внедрении.')]
CSS='''
:root{--paper:#fffef9;--ink:#1a1a1a;--muted:#333333;--accent:#33567a;--hairline:rgba(26,26,26,.18);--rule:rgba(26,26,26,.25)}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:400 17px/1.62 'PT Serif',Georgia,'Times New Roman',serif}.page{max-width:740px;margin:0 auto;padding:72px 22px 64px}.masthead{padding-bottom:30px}h1{font-size:1.9em;line-height:1.15;font-weight:400;margin:0 0 16px}.lede{font-size:1.1em;line-height:1.58;color:var(--muted);margin:0}h2{font-size:1.4em;line-height:1.3;font-weight:400;margin:0 0 14px}h3{font-size:1.1em;font-weight:700;margin:30px 0 12px}p{margin:0 0 1em}a{color:var(--accent);text-decoration-thickness:1px;text-underline-offset:2px}a:hover{color:var(--ink)}a:focus-visible{outline:2px solid var(--accent);outline-offset:4px}nav.toc{margin:26px 0 54px}nav.toc ul{list-style:none;margin:0;padding:0}nav.toc li{font:400 12.5px/2.1 'PT Mono',ui-monospace,monospace}nav.toc a{color:var(--accent);text-decoration:none}nav.toc a:hover{text-decoration:underline;text-underline-offset:2px}section{padding:44px 0 0}section:first-of-type{padding-top:0}figure{margin:22px 0 26px}figure img{display:block;width:100%;height:auto}figure.diagram{width:114%;max-width:860px;margin:0 0 24px -7%}figure.diagram svg{display:block;width:100%;height:auto}figure.diagram svg text{font-family:'PT Mono',Menlo,Monaco,Consolas,monospace}figure.diagram svg text[font-weight="600"]{font-family:system-ui,-apple-system,sans-serif}figcaption{font:400 11px/1.6 'PT Mono',monospace;color:var(--muted);margin-top:10px;text-align:center}.comparison{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;width:min(1240px,calc(100vw - 64px));position:relative;left:50%;transform:translateX(-50%);margin:0 0 26px}.comparison h3{margin:16px 0 12px}.comparison figure{margin:0 0 14px}.comparison .source{margin:0}.source{font:400 11px/1.6 'PT Mono',monospace;color:var(--muted)}.plain{list-style:none;margin:0 0 1em;padding:0}.plain li{margin:0 0 12px}.footer{margin-top:44px;font-size:.96em;color:var(--muted)}@media print{@page{size:A4;margin:20mm 17mm}body{font-size:10.5pt;line-height:1.55}.page{max-width:none;padding:0}h1,h2,h3{break-after:avoid}figure{break-inside:avoid}.comparison{width:100%;gap:16px}section{padding-top:26pt}}
'''
def esc(s):return html.escape(s)
def frame(key,side,title):
 name=f'{side}-{key}.png';data=base64.b64encode((R/'screens'/name).read_bytes()).decode()
 return f'<figure><a href="screens/{name}" target="_blank" rel="noopener"><img width="1440" height="900" src="data:image/png;base64,{data}" alt="{esc(title)}"></a><figcaption>{esc(title)}. 1440 × 900. <a href="screens/{name}" target="_blank" rel="noopener">Открыть в полном размере</a></figcaption></figure>'
diagram='<figure class="diagram">'+(R/'transition-diagram.svg').read_text()+'<figcaption>Рис. 1. Выбор оформления предшествует изменениям на сайте.</figcaption></figure><p>Сравните главную и пост ниже: размер текста, положение видео и обложки. Выбранное оформление станет основой для остальных страниц.</p>'
body='<header class="masthead"><h1>Бумажный дизайн sereja.tech</h1><p class="lede">Главная, посты и остальные страницы в оформлении учебных гайдов: светлая бумага, спокойная типографика и одна колонка.</p></header>'+diagram+'<nav class="toc" aria-label="Содержание"><ul>'+''.join(f'<li><a href="#{k}">{title}</a></li>' for k,title,_,_ in pages)+'<li><a href="#transition">Порядок перехода</a></li></ul></nav>'
body+='<p>Текущие страницы сняты с <a href="https://sereja.tech/">sereja.tech</a> в браузере с вашей тёмной темой.</p>'
for key,title,url,note in pages:
 body+=f'<section id="{key}"><h2>{title}</h2><div class="comparison"><div class="comparison-side"><h3>Было</h3>'+frame(key,'before',f'{title} — текущий сайт в тёмной теме')+f'<p class="source"><a href="https://sereja.tech{url}" target="_blank" rel="noopener">Открыть текущую страницу</a></p></div><div class="comparison-side"><h3>Будет</h3>'+frame(key,'after',f'{title} — предлагаемый бумажный дизайн')+f'<p class="source"><a href="after-{key}.html" target="_blank" rel="noopener">Открыть макет целиком</a></p></div></div><p>{esc(note)}</p>'
 if key=='post':body+='<p>В макете также доступны <a href="after-post.html#контракт-для-агента" target="_blank" rel="noopener">раскрытие и копирование промпта</a>, содержание статьи и переходы к связанным материалам.</p>'
 if key=='rich':body+='<p><a href="after-rich.html#usilie" target="_blank" rel="noopener">Посмотреть графики</a> и <a href="after-rich.html#prompting" target="_blank" rel="noopener">промпт</a>.</p>'
 body+='</section>'
body+='''<section id="transition"><h2>Порядок перехода</h2><ol><li><strong>Выбрать главную и пост.</strong> Проверить размер текста, длину строки и порядок блоков. Видеоблок на главной и обложка над заголовком поста включены по вашим комментариям.</li><li><strong>Перенести общую типографику.</strong> Использовать бумагу #fffef9, чернила #1a1a1a, приглушённый синий #33567a, PT Serif и PT Mono. Текстовая колонка — 740 px.</li><li><strong>Оформить остальные страницы.</strong> Применить ту же систему к блогу, поиску, темам, биографии, ссылкам и ошибке.</li><li><strong>Перенести содержимое постов.</strong> Сохранить текст, изображения, видео, источники, графики и копирование. Проверить длинные материалы целиком.</li><li><strong>Проверить и выпустить.</strong> Сверить страницы на десктопе, ссылки, сборку и поисковые сигналы. После выбора результата выпустить через связанный Git-репозиторий.</li></ol><p><strong>Готово, когда</strong> все страницы читаются как одна система, поиск и переходы работают, а тексты и адреса статей сохранены.</p></section><p class="footer">Первая версия проверяется только на десктопе. Мобильная проверка отложена по вашему запросу.</p>'''
page='<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Бумажный дизайн sereja.tech</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=PT+Serif:ital,wght@0,400;0,700;1,400&family=PT+Mono&display=swap" rel="stylesheet"><style>'+CSS+'</style></head><body><main class="page">'+body+'</main></body></html>'
(R/'plan.html').write_text(page)
print('Built paper plan: opening SVG, 9 pages, 18 screenshots')
