#!/usr/bin/env python3
"""Sync data/videos.yml from the YouTube channel RSS feed.

Generated by scripts/sync-videos.py, руками не править.

Fetches the channel's public RSS feed, takes the 4 most recent entries,
and rewrites data/videos.yml. Exits 1 (without touching the file) if the
feed is unreachable or yields fewer than 4 entries. If the rendered file
is identical to what's already on disk, exits 0 without writing.
"""

import sys
import urllib.request
import urllib.error
import xml.etree.ElementTree as ET
from pathlib import Path

RSS_URL = "https://www.youtube.com/feeds/videos.xml?channel_id=UCH6k750mdcOXU6PYHSCOlrA"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "data" / "videos.yml"
REQUIRED_COUNT = 4

NS = {
    "atom": "http://www.w3.org/2005/Atom",
    "yt": "http://www.youtube.com/xml/schemas/2015",
}

HEADER = (
    "# Последние YouTube-видео/стримы. Первый = featured (iframe на главной).\n"
    "# Generated by scripts/sync-videos.py, руками не править.\n"
)


def fetch_feed(url: str) -> bytes:
    with urllib.request.urlopen(url, timeout=30) as resp:
        return resp.read()


def parse_entries(xml_bytes: bytes):
    root = ET.fromstring(xml_bytes)
    entries = []
    for entry in root.findall("atom:entry", NS):
        video_id_el = entry.find("yt:videoId", NS)
        title_el = entry.find("atom:title", NS)
        published_el = entry.find("atom:published", NS)
        if video_id_el is None or title_el is None or published_el is None:
            continue
        video_id = (video_id_el.text or "").strip()
        title = (title_el.text or "").strip()
        published = (published_el.text or "").strip()
        date = published[:10] if len(published) >= 10 else ""
        if not (video_id and title and date):
            continue
        entries.append({"id": video_id, "title": title, "date": date})
    return entries


def escape_yaml_double_quoted(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_yaml(entries) -> str:
    lines = [HEADER, "videos:"]
    for entry in entries:
        title = escape_yaml_double_quoted(entry["title"])
        lines.append(f"  - id: {entry['id']}")
        lines.append(f'    title: "{title}"')
        lines.append(f"    date: {entry['date']}")
    return "\n".join(lines) + "\n"


def main() -> int:
    try:
        xml_bytes = fetch_feed(RSS_URL)
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        print(f"sync-videos: failed to fetch RSS feed: {exc}", file=sys.stderr)
        return 1

    try:
        entries = parse_entries(xml_bytes)
    except ET.ParseError as exc:
        print(f"sync-videos: failed to parse RSS feed: {exc}", file=sys.stderr)
        return 1

    if len(entries) < REQUIRED_COUNT:
        print(
            f"sync-videos: expected at least {REQUIRED_COUNT} entries, got {len(entries)}",
            file=sys.stderr,
        )
        return 1

    new_content = render_yaml(entries[:REQUIRED_COUNT])

    if OUTPUT_PATH.exists() and OUTPUT_PATH.read_text(encoding="utf-8") == new_content:
        print("sync-videos: no changes")
        return 0

    OUTPUT_PATH.write_text(new_content, encoding="utf-8")
    print(f"sync-videos: wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
